name: SkyblockCommands
main: pw.untamemadman.plugins.SkyBlockCommands.SkyBlockCommands
version: ${version}
commands:
  skyblock:
    description: The generic Skyblock command.
    usage: /skyblock <start/restart>